import { drizzle } from "drizzle-orm/mysql2";
import { films, streamingPlatforms } from "./drizzle/schema.js";
Show less
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}
const db = drizzle(DATABASE_URL);
const platformsData = [
  { name: "Tubi", slug: "tubi", color: "#FF0000" },
  { name: "HBO Max", slug: "hbo-max", color: "#9E1B32" },
  { name: "Netflix", slug: "netflix", color: "#E50914" },
  { name: "Plex", slug: "plex", color: "#FFB000" },
  { name: "Hulu", slug: "hulu", color: "#1CE783" },
  { name: "Disney+", slug: "disney-plus", color: "#113CCF" },
  { name: "Prime Video", slug: "prime-video", color: "#00A8E1" },
  { name: "YouTube", slug: "youtube", color: "#FF0000" },
  { name: "Pluto TV", slug: "pluto-tv", color: "#000000" },
  { name: "MGM+", slug: "mgm-plus", color: "#FFA500" },
  { name: "Starz", slug: "starz", color: "#000000" },
];
const filmsData = [
  {
    title: "Under the Silver Lake",
    year: 2018,
    synopsis: "A drifter investigates the disappearance of a woman in Los Angeles, uncovering a web of conspiracy and mystery in the city's underbelly.",
    genres: "Neo-Noir, Mystery, Thriller",
    imdbId: "tt5691994",
    imdbUrl: "https://www.imdb.com/title/tt5691994/",
    imdbRating: "6.8/10",
    rottenTomatoesScore: "52%",
    posterUrl: "https://image.tmdb.org/t/p/w500/cJ9aKlEgTLYtpYjNqin06YqJRUl.jpg",
    directors: JSON.stringify(["David Robert Mitchell"]),
    cast: JSON.stringify(["Andrew Garfield", "Callie Hernandez", "Matthew Gray Gubler"]),
    runtime: 139,
  },
  {
    title: "Inherent Vice",
    year: 2014,
    synopsis: "A stoned private detective in 1970s Los Angeles investigates the disappearance of a former lover and uncovers a complex web of corruption.",
    genres: "Neo-Noir, Comedy, Mystery",
    imdbId: "tt1791528",
    imdbUrl: "https://www.imdb.com/title/tt1791528/",
    imdbRating: "7.0/10",
    rottenTomatoesScore: "75%",
    posterUrl: "https://image.tmdb.org/t/p/w500/hyan5Uc0lGpPuad94DM1pLxneiP.jpg",
    directors: JSON.stringify(["Paul Thomas Anderson"]),
    cast: JSON.stringify(["Joaquin Phoenix", "Josh Brolin", "Katherine Waterston"]),
    runtime: 148,
  },
  {
    title: "Mulholland Drive",
    year: 2001,
    synopsis: "After a car accident on Mulholland Drive, an aspiring actress helps a woman with amnesia while navigating the dark underbelly of Hollywood.",
    genres: "Neo-Noir, Drama, Mystery",
    imdbId: "tt0166924",
    imdbUrl: "https://www.imdb.com/title/tt0166924/",
    imdbRating: "8.0/10",
    rottenTomatoesScore: "87%",
    posterUrl: "https://image.tmdb.org/t/p/w500/tVxGt7uffLVhIIcwuldXOMpFBPX.jpg",
    directors: JSON.stringify(["David Lynch"]),
    cast: JSON.stringify(["Naomi Watts", "Laura Elena Harring", "Justin Theroux"]),
    runtime: 147,
  },
  {
    title: "Collateral",
    year: 2004,
    synopsis: "A taxi driver is forced to become an accomplice in a series of contract killings while driving a mysterious passenger through Los Angeles.",
    genres: "Neo-Noir, Thriller, Crime",
    imdbId: "tt0369339",
    imdbUrl: "https://www.imdb.com/title/tt0369339/",
    imdbRating: "7.5/10",
    rottenTomatoesScore: "87%",
    posterUrl: "https://image.tmdb.org/t/p/w500/nV5316WUsVij8sVXLCF1g7TFitg.jpg",
    directors: JSON.stringify(["Michael Mann"]),
    cast: JSON.stringify(["Tom Cruise", "Jamie Foxx", "Jada Pinkett Smith"]),
    runtime: 120,
  },
  {
    title: "LA Confidential",
    year: 1997,
    synopsis: "Two detectives in 1950s Los Angeles uncover corruption and murder while investigating a brutal crime in the city's criminal underworld.",
    genres: "Neo-Noir, Crime, Drama",
    imdbId: "tt0119506",
    imdbUrl: "https://www.imdb.com/title/tt0119506/",
    imdbRating: "8.2/10",
    rottenTomatoesScore: "90%",
    posterUrl: "https://image.tmdb.org/t/p/w500/lWCgf5sD5FpMljjpkRhcC8pXcch.jpg",
    directors: JSON.stringify(["Curtis Hanson"]),
    cast: JSON.stringify(["Russell Crowe", "Guy Pearce", "Kim Basinger"]),
    runtime: 138,
  },
  {
    title: "Blade Runner",
    year: 1982,
    synopsis: "In a futuristic Los Angeles, a blade runner hunts down rogue androids while questioning his own humanity.",
    genres: "Neo-Noir, Sci-Fi, Thriller",
    imdbId: "tt0083658",
    imdbUrl: "https://www.imdb.com/title/tt0083658/",
    imdbRating: "8.1/10",
    rottenTomatoesScore: "89%",
    posterUrl: "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    directors: JSON.stringify(["Ridley Scott"]),
    cast: JSON.stringify(["Harrison Ford", "Rutger Hauer", "Sean Young"]),
    runtime: 117,
  },
  {
    title: "Brick",
    year: 2005,
    synopsis: "A high school student investigates the murder of his ex-girlfriend using noir detective conventions in a modern suburban setting.",
    genres: "Neo-Noir, Mystery, Crime",
    imdbId: "tt0393109",
    imdbUrl: "https://www.imdb.com/title/tt0393109/",
    imdbRating: "7.4/10",
    rottenTomatoesScore: "81%",
    posterUrl: "https://image.tmdb.org/t/p/w500/5WVk8JpNIxepn4fpZzQeCumkOL5.jpg",
    directors: JSON.stringify(["Rian Johnson"]),
    cast: JSON.stringify(["Joseph Gordon-Levitt", "Nora Zehetner", "Lukas Haas"]),
    runtime: 110,
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    synopsis: "Multiple interconnected stories of Los Angeles criminals, gangsters, and hitmen unfold in a non-linear narrative.",
    genres: "Neo-Noir, Crime, Drama",
    imdbId: "tt0110912",
    imdbUrl: "https://www.imdb.com/title/tt0110912/",
    imdbRating: "8.9/10",
    rottenTomatoesScore: "92%",
    posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    directors: JSON.stringify(["Quentin Tarantino"]),
    cast: JSON.stringify(["John Travolta", "Samuel L. Jackson", "Uma Thurman"]),
    runtime: 154,
  },
  {
    title: "Fear and Loathing in Las Vegas",
    year: 1998,
    synopsis: "A journalist and his attorney venture to Las Vegas to cover a motorcycle race, descending into a drug-fueled odyssey.",
    genres: "Neo-Noir, Comedy, Drama",
    imdbId: "tt0120669",
    imdbUrl: "https://www.imdb.com/title/tt0120669/",
    imdbRating: "7.7/10",
    rottenTomatoesScore: "68%",
    posterUrl: "https://image.tmdb.org/t/p/w500/tisNLcMkxryU2zxhi0PiyDFqhm0.jpg",
    directors: JSON.stringify(["Terry Gilliam"]),
    cast: JSON.stringify(["Johnny Depp", "Benicio Del Toro", "Tobey Maguire"]),
    runtime: 118,
  },
  {
    title: "Once Upon a Time in Hollywood",
    year: 2019,
    synopsis: "A fading actor and his stunt double navigate the film industry in 1960s Los Angeles as the Manson murders loom.",
    genres: "Neo-Noir, Drama, Comedy",
    imdbId: "tt1723121",
    imdbUrl: "https://www.imdb.com/title/tt1723121/",
    imdbRating: "7.6/10",
    rottenTomatoesScore: "85%",
    posterUrl: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
    directors: JSON.stringify(["Quentin Tarantino"]),
    cast: JSON.stringify(["Leonardo DiCaprio", "Brad Pitt", "Margot Robbie"]),
    runtime: 161,
  },
  {
    title: "The Big Lebowski",
    year: 1998,
    synopsis: "A laid-back bowling bum is mistaken for a millionaire and drawn into a kidnapping plot in Los Angeles.",
    genres: "Neo-Noir, Comedy, Crime",
    imdbId: "tt0118715",
    imdbUrl: "https://www.imdb.com/title/tt0118715/",
    imdbRating: "8.1/10",
    rottenTomatoesScore: "80%",
    posterUrl: "https://image.tmdb.org/t/p/w500/9mprbw31MGdd66LR0AQKoDMoFRv.jpg",
    directors: JSON.stringify(["Joel Coen", "Ethan Coen"]),
    cast: JSON.stringify(["Jeff Bridges", "John Goodman", "Julianne Moore"]),
    runtime: 117,
  },
  {
    title: "Drive",
    year: 2011,
    synopsis: "A getaway driver for criminals lives a quiet life until he gets involved with a woman and her son, leading to violent consequences.",
    genres: "Neo-Noir, Crime, Thriller",
    imdbId: "tt0780504",
    imdbUrl: "https://www.imdb.com/title/tt0780504/",
    imdbRating: "7.8/10",
    rottenTomatoesScore: "93%",
    posterUrl: "https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    directors: JSON.stringify(["Nicolas Winding Refn"]),
    cast: JSON.stringify(["Ryan Gosling", "Carey Mulligan", "Bryan Cranston"]),
    runtime: 100,
  },
  {
    title: "Nightcrawler",
    year: 2014,
    synopsis: "An ambitious freelance videographer in Los Angeles becomes increasingly obsessed with capturing violent crimes on camera.",
    genres: "Neo-Noir, Thriller, Crime",
    imdbId: "tt2872718",
    imdbUrl: "https://www.imdb.com/title/tt2872718/",
    imdbRating: "7.9/10",
    rottenTomatoesScore: "96%",
    posterUrl: "https://image.tmdb.org/t/p/w500/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    directors: JSON.stringify(["Dan Gilroy"]),
    cast: JSON.stringify(["Jake Gyllenhaal", "Rene Russo", "Riz Ahmed"]),
    runtime: 117,
  },
  {
    title: "Crash",
    year: 1996,
    synopsis: "A group of people in Los Angeles discover a sexual fetish for car crashes, leading to dangerous and destructive behavior.",
    genres: "Neo-Noir, Drama, Thriller",
    imdbId: "tt0115964",
    imdbUrl: "https://www.imdb.com/title/tt0115964/",
    imdbRating: "6.3/10",
    rottenTomatoesScore: "39%",
    posterUrl: "https://image.tmdb.org/t/p/w500/gpai5oUFyFGLHOCsYTvVMqlbY7A.jpg",
    directors: JSON.stringify(["David Cronenberg"]),
    cast: JSON.stringify(["James Spader", "Debbie Unger", "Elias Koteas"]),
    runtime: 100,
  },
  {
    title: "Spun",
    year: 2002,
    synopsis: "A meth addict in Los Angeles experiences a chaotic, drug-fueled journey through the criminal underworld.",
    genres: "Neo-Noir, Crime, Drama",
    imdbId: "tt0283003",
    imdbUrl: "https://www.imdb.com/title/tt0283003/",
    imdbRating: "6.5/10",
    rottenTomatoesScore: "42%",
    posterUrl: "https://image.tmdb.org/t/p/w500/jiwNobUsd29ooowQyTeh0cvPBFL.jpg",
    directors: JSON.stringify(["Jonas Akerlund"]),
    cast: JSON.stringify(["Jason Schwartzman", "Brittany Murphy", "Mickey Rourke"]),
    runtime: 111,
  },
  {
    title: "Southland Tales",
    year: 2006,
    synopsis: "In a dystopian future Los Angeles, multiple characters' lives intersect in a complex narrative involving surveillance and conspiracy.",
    genres: "Neo-Noir, Sci-Fi, Drama",
    imdbId: "tt0405336",
    imdbUrl: "https://www.imdb.com/title/tt0405336/",
    imdbRating: "5.5/10",
    rottenTomatoesScore: "29%",
    posterUrl: "https://image.tmdb.org/t/p/w500/thGIvfayC2aIS6V8je6w0DmJn4z.jpg",
    directors: JSON.stringify(["Richard Kelly"]),
    cast: JSON.stringify(["Dwayne Johnson", "Seann William Scott", "Sarah Michelle Gellar"]),
    runtime: 144,
  },
  {
    title: "Street Kings",
    year: 2008,
    synopsis: "A corrupt LAPD detective investigates the murder of his partner while navigating the dangerous world of street crime.",
    genres: "Neo-Noir, Crime, Thriller",
    imdbId: "tt0560009",
    imdbUrl: "https://www.imdb.com/title/tt0560009/",
    imdbRating: "6.6/10",
    rottenTomatoesScore: "54%",
    posterUrl: "https://image.tmdb.org/t/p/w500/csXyZ1BsDBlH0PXkOFWxggEf9WF.jpg",
    directors: JSON.stringify(["David Ayer"]),
    cast: JSON.stringify(["Keanu Reeves", "Forest Whitaker", "Hugh Laurie"]),
    runtime: 109,
  },
  {
    title: "Training Day",
    year: 2001,
    synopsis: "A rookie LAPD officer works with a veteran detective who is revealed to be corrupt, leading to a moral crisis.",
    genres: "Neo-Noir, Crime, Drama",
    imdbId: "tt0139654",
    imdbUrl: "https://www.imdb.com/title/tt0139654/",
    imdbRating: "7.4/10",
    rottenTomatoesScore: "76%",
    posterUrl: "https://image.tmdb.org/t/p/w500/bUeiwBQdupBLQthMCHKV7zv56uv.jpg",
    directors: JSON.stringify(["Antoine Fuqua"]),
    cast: JSON.stringify(["Denzel Washington", "Ethan Hawke", "Scott Glenn"]),
    runtime: 122,
  },
  {
    title: "Friday",
    year: 1995,
    synopsis: "Two friends spend a day in South Central Los Angeles dealing with neighborhood drama, crime, and comedy.",
    genres: "Neo-Noir, Comedy, Crime",
    imdbId: "tt0113118",
    imdbUrl: "https://www.imdb.com/title/tt0113118/",
    imdbRating: "7.3/10",
    rottenTomatoesScore: "76%",
    posterUrl: "https://image.tmdb.org/t/p/w500/2lReF53F8trkC68piGSfk0JVwWU.jpg",
    directors: JSON.stringify(["F. Gary Gray"]),
    cast: JSON.stringify(["Ice Cube", "Chris Tucker", "Nia Long"]),
    runtime: 91,
  },
];
async function seed() {
  try {
    console.log("Starting database seed...");
    console.log("Inserting streaming platforms...");
    for (const platform of platformsData) {
      await db.insert(streamingPlatforms).values(platform).catch(() => {});
    }
    console.log("Inserting films...");
    for (const film of filmsData) {
      await db.insert(films).values(film).catch(() => {});
    }
    console.log("Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  }
}
seed();
